version: '3.4'

services:
  catalogdb:
    image: mongo
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile
  basket.api:
    image: ${DOCKER_REGISTRY-}basket
    build:
      context: .
      dockerfile: src/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
