version: '3.4'

services:
  catalogdb:
    container_name: catalogdb
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  orderdb:
    container_name: orderdb
    restart: always
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=shockz99!@
      - ACCEPT_EULA=Y

  catalog.api:
    container_name: catalogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  basket.api:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:Redis=basketdb:6379"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"

  ordering.api:
    container_name: orderingapi
    restart: on-failure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderConnection=Server=orderdb;Database=OrderDb;User Id=sa;Password=shockz99!@;"
      - "EventBus:HostName=rabbitmq"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8002:80"

  ocelotapigateway:
    container_name: ocelotapigateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - catalog.api
      - basket.api
      - ordering.api
    ports:
      - "7000:80"

